Autos.AppWebMvc/Models/ErrorViewModel.cs
namespace Autos.AppWebMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Autos.AppWebMvc/Controllers/AutosController.cs
using Autos.DTOs.Autos.DTOs;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Autos.AppWebMvc.Controllers
{
    public class AutosController : Controller
    {
        private readonly HttpClient _httpClientAutoAPI;
        public AutosController(IHttpClientFactory httpClientFactory)
        {
            _httpClientAutoAPI = httpClientFactory.CreateClient("AutoAPI");
        }

        // GET: AutosController
        public async Task<IActionResult> Index(SearchQueryAutoDTO searchQueryAutoDTO, int CountRow = 0)
        {
            if (searchQueryAutoDTO.SendRowCount == 0)
                searchQueryAutoDTO.SendRowCount = 2;
            if (searchQueryAutoDTO.Take == 0)
                searchQueryAutoDTO.Take = 10;

            var result = new SearchResultAutoDTO();
            var response = await _httpClientAutoAPI.PostAsJsonAsync("/auto/search", searchQueryAutoDTO);

            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<SearchResultAutoDTO>();

            result = result != null ? result : new SearchResultAutoDTO();

            if (result.CountRow == 0 && searchQueryAutoDTO.SendRowCount == 1)
                result.CountRow = CountRow;

            ViewBag.CountRow = result.CountRow;
            searchQueryAutoDTO.SendRowCount = 0;
            ViewBag.SearchQuery = searchQueryAutoDTO;

            return View(result);
        }

        // GET: AutosController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var result = new GetIdResultAuto();
            var response = await _httpClientAutoAPI.GetAsync("/auto/" + id);

            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<GetIdResultAuto>();

            return View(result ?? new GetIdResultAuto());
        }

        // GET: AutosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AutosController/Create
        [HttpPost]
        public async Task<IActionResult> Create(CreateAutoDTO createAutoDTO)
        {
            try
            {
                var response = await _httpClientAutoAPI.PostAsJsonAsync("/auto", createAutoDTO);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }

                ViewBag.Error = "Error al ingresar los datos";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: AutosController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var result = new GetIdResultAuto();
            var response = await _httpClientAutoAPI.GetAsync("/auto/" + id);

            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<GetIdResultAuto>();

            return View(new EditAutoDTO(result ?? new GetIdResultAuto()));
        }

        // POST: AutosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditAutoDTO editAutoDTO)
        {
            try
            {
                var response = await _httpClientAutoAPI.PostAsJsonAsync("/auto", editAutoDTO);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Error = "Error al editar los datos";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: AutosController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var result = new GetIdResultAuto();
            var response = await _httpClientAutoAPI.GetAsync("/auto/" + id);

            if (response.IsSuccessStatusCode)
                result = await response.Content.ReadFromJsonAsync<GetIdResultAuto>();

            return View(result ?? new GetIdResultAuto());
        }

        // POST: AutosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, GetIdResultAuto get)
        {
            try
            {
                var response = await _httpClientAutoAPI.DeleteAsync("/auto/" + id);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Error = "Error al eliminar los datos";
                return View(get);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(get);
            }
        }
    }
}

Autos.AppWebMvc/Controllers/HomeController.cs
using Autos.AppWebMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Autos.AppWebMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Autos.AppWebMvc/Views/Autos/Create.cshtml
@model Autos.DTOs.Autos.DTOs.CreateAutoDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Auto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" name="subir" value="Crear" class="btn btn-primary" />
                <a asp-action="Index" name="regresar" class="btn btn-primary">Regresar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Autos.AppWebMvc/Views/Autos/Delete.cshtml
@model Autos.DTOs.Autos.DTOs.GetIdResultAuto

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Esta seguro de eliminar este registro?</h3>
<div>
    <h4>Autos</h4>
    <hr />
    <dl class="row border-1">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-outline-dark">Regresar</a>
    </form>
</div>

Autos.AppWebMvc/Views/Autos/Details.cshtml
@model Autos.DTOs.Autos.DTOs.GetIdResultAuto

@{
    ViewData["Title"] = "Details";
}
<h1>Detalles</h1>
<div>
    <h4>Autos</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-secondary">Editar</a> |
    <a asp-action="Index" class="btn btn-outline-secondary">Regresar</a>
</div>

Autos.AppWebMvc/Views/Autos/Edit.cshtml
@model Autos.DTOs.Autos.DTOs.EditAutoDTO

@{
    ViewData["Title"] = "Edit";
}
<h1>Editar</h1>
<h4>Auto</h4>
<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input asp-for="Id" type="hidden" />
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="form-group">
            <input type="submit" value="Modificar" class="btn btn-primary" /> |
            <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Autos.AppWebMvc/Views/Autos/Index.cshtml
@model SearchResultAutoDTO
@{
    ViewData["Title"] = "Index";
    var modelSearchQuery = ViewBag.SearchQuery as SearchQueryAutoDTO;
}
<partial name="SearchQuery" model="modelSearchQuery" />
<partial name="SearchResult" model="Model.Data" />

Autos.AppWebMvc/Views/Autos/SearchQuery.cshtml
@model SearchQueryAutoDTO
@{
    int totalRegistros = (int)ViewBag.CountRow;
    int totalPaginas = (int)Math.Ceiling((double)totalRegistros / Model.Take);
}

<h4>Buscar Auto</h4>
<hr/>
<div class="row">
    <form asp-action="Index">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="SendRowCount" type="hidden" id="txtSendRowCount"/>
        <input asp-for="Skip" type="hidden" id="txtSkip"/>
        <input name="CountRow" value="@totalRegistros" type="hidden" />
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="Marca_Like" class="control-label"></label>
                    <input asp-for="Marca_Like" class="form-control" />
                    <span asp-validation-for="Marca_Like" class="text-danger"></span>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="Modelo_Like" class="control-label"></label>
                    <input asp-for="Modelo_Like" class="form-control" />
                    <span asp-validation-for="Modelo_Like" class="text-danger"></span>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <label asp-for="Take" class="control-label"></label>
                    <select asp-for="Take" class="form-control">
                        @for(var i = 10; i < 1000; i += 10)
                        {
                            if(i == Model.Take)
                            {
                                <option selected value="@i">@i</option>
                            }
                            else
                            {
                                <option value="@i">@i</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="Take" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <input type="submit" id="btnSearch" value="Buscar" class="btn btn-primary" />
                    <a asp-action="Create" name="crear" class="btn btn-primary">Ir a crear</a>
                </div>
            </div>
        </div>
        <br />
        <div class="row" style="overflow:auto !important">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @{
                        int skipAnte = Model.Skip > 0 ? Model.Skip - Model.Take : 0;
                        int skipMax = 0;
                    }
                    <li class="page-item"><a class="page-link" data-skip="@skipAnte" href="#" onclick="pagiancion(this)">Anterior</a></li>
                    @for(var i = 0; i < totalPaginas; i++)
                    {
                        int skip = i * Model.Take;
                        int numPag = i + 1; 
                        if(skip != Model.Skip)
                        {
                            <li class="page-item"><a class="page-link" data-skip="@skipAnte" href="#" onclick="pagiancion(this)">@numPag</a></li>
                        }
                        else
                        {
                            <li class="page-item active"><a class="page-link" data-skip="@skipAnte" href="#" onclick="pagiancion(this)">@numPag</a></li>
                        }
                        skipMax = skip;
                    }
                    @{
                        int skipSi = Model.Skip + Model.Take;
                        skipSi = skipSi > skipMax ? skipSi - Model.Take : skipSi;
                    }
                    <li class="page-item"><a class="page-link" data-skip="@skipSi" href="#" onclick="pagiancion(this)">Siguiente</a></li>
                </ul>
            </nav>
        </div>
        <div class="row-cols-6">
            <span>Total registros: @totalRegistros</span>
        </div>
    </form>
</div>

<script>
    function paginacion(li){
        const skip = li.getAttribute("data-skip");
        const btnSearch = document.getElementById("btnSearch");
        const txtSkip = document.getElementById("txtSkip");
        const txtSendRowCount = document.getElementById("txtSendRowCount");
        txtSkip.value = skip;
        txtSendRowCount.value = 1;
        btnSearch.click();
    }
</script>

Autos.AppWebMvc/Views/Autos/SearchResult.cshtml
@model IEnumerable<SearchResultAutoDTO.AutosDTO>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(item => item.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(item => item.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(item => item.Year)
            </th>
            <th>
                @Html.DisplayNameFor(item => item.Precio)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null){
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.ActionLink("Modificar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Ver", "Details", new { id = item.Id }, new { @class = "btn btn-secondary" }) |
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
        }
       
    </tbody>
</table>

Autos.AppWebMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Autos.AppWebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Autos.AppWebMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Autos.AppWebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Autos.AppWebMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fas fa-list" asp-area="" asp-controller="Autos" asp-action="Index">Catálogo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Autos.AppWebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>